title: "COD Guides"
description: "Гайды по Call of Dragons"
baseurl: "/COD-Guides"
url: "https://kolya-yt.github.io"
markdown: kramdown
permalink: pretty
collections:
  guides:
    output: true
    permalink: /guides/:name/
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

# GoatCounter site code (for real pageview counters). Example: "abc123"
goatcounter_code: "abdce"

# Pages asset refresh
